<?php
	
	namespace Quellabs\Discover\Utilities;
	
	/**
	 * Handles loading and parsing Composer's installed packages data
	 * Supports both modern PHP format (installed.php) and legacy JSON format (installed.json)
	 * Uses PSR4 utility class for file path resolution
	 */
	class ComposerInstalledLoader {
		
		/**
		 * @var ComposerPathResolver Path resolution utility
		 */
		private ComposerPathResolver $pathResolver;
		
		/**
		 * @var array<string, array|null> Cache of parsed installed files
		 */
		private array $installedDataCache = [];
		
		/**
		 * Directory to start searching from (defaults to current directory)
		 * @var string|null
		 */
		private ?string $startDirectory;
		
		/**
		 * Constructor
		 * @param ComposerPathResolver|null $pathResolver Optional PSR4 instance (creates new one if not provided)
		 * @param string|null $startDirectory Directory to start searching from (defaults to current directory)
		 */
		public function __construct(
			?ComposerPathResolver $pathResolver = null,
			?string $startDirectory = null
		) {
			$this->pathResolver = $pathResolver ?? new ComposerPathResolver();
			$this->startDirectory = $startDirectory;
		}
		
		/**
		 * Parse and return installed packages data with caching
		 * Automatically handles both PHP and JSON formats, preferring PHP
		 * @return array|null Parsed installed packages data or null on failure
		 */
		public function getData(): ?array {
			// Try the cache file first (generated by ServiceDiscoveryPlugin)
			$mappingPath = $this->pathResolver->getDiscoveryMappingPath($this->startDirectory);
			
			if ($mappingPath !== null) {
				// Found a mapping file, pull it in
				return $this->installedDataCache[$mappingPath] = include $mappingPath;
			}
			
			// Fallback to JSON format (legacy Composer)
			// JSON format is used by older Composer versions and when lockfile is unavailable
			$jsonPath = $this->pathResolver->getComposerInstalledJsonPath($this->startDirectory);
			
			if ($jsonPath !== null) {
				// Found installed.json file, attempt to load and parse it
				return $this->installedDataCache[$jsonPath] = $this->parseJsonFile($jsonPath);
			}
			
			// No installed packages file found in either format
			return null;
		}
		
		/**
		 * Parse a JSON file and return package extra data as an array
		 * @param string $filePath Path to the JSON file
		 * @return array Parsed extra data as "package-name" => extra_block
		 */
		protected function parseJsonFile(string $filePath): array {
			// Check if the file exists and is readable
			if (!is_readable($filePath)) {
				return [];
			}
			
			// Read the entire file contents into a string
			$content = file_get_contents($filePath);
			
			// Check if file reading was successful
			if ($content === false) {
				return [];
			}
			
			// Decode the JSON string into a PHP array
			// The second parameter 'true' ensures we get an associative array instead of objects
			$data = json_decode($content, true);
			
			// Check if JSON parsing was successful by examining the last JSON error
			if (json_last_error() !== JSON_ERROR_NONE) {
				return [];
			}
			
			// Extract the packages array
			if (isset($data['packages'])) {
				$packages = $data['packages'];
			} elseif (is_array($data) && $this->isPackageArray($data)) {
				$packages = $data;
			} else {
				return [];
			}
			
			// Extract extra blocks from packages
			$extraMap = [];
			
			foreach ($packages as $package) {
				if (isset($package['name']) && !empty($package['extra'])) {
					$extraMap[$package['name']] = $package['extra'];
				}
			}
			
			return $extraMap;
		}
		
		/**
		 * Check if the array appears to be a direct array of packages
		 * @param array $data Data to check
		 * @return bool True if it looks like a package array
		 */
		private function isPackageArray(array $data): bool {
			// Check if it's a numerically indexed array with package-like objects
			if (empty($data) || !isset($data[0])) {
				return false;
			}
			
			// Check if the first element has package-like structure
			$firstElement = $data[0];
			return is_array($firstElement) && isset($firstElement['name']);
		}
	}